#!/bin/bash

/usr/bin/apt update -y

/usr/bin/apt upgrade -y

/usr/bin/apt install python3 python3-pip -y

/usr/bin/python3 -m pip install boto3

/usr/bin/apt install nginx -y

/usr/bin/apt install git -y
